# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=45, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=45, verbose_name='Address line 2')),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state_province', models.CharField(blank=True, max_length=40, verbose_name='State/Province')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=2000)),
                ('start_time', models.CharField(max_length=1000)),
                ('end_time', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigator_notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MetricsSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('county', models.CharField(default='', max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('no_general_assis', models.IntegerField(default=0)),
                ('no_plan_usage_assis', models.IntegerField(default=0)),
                ('no_locating_provider_assis', models.IntegerField(default=0)),
                ('no_billing_assis', models.IntegerField(default=0)),
                ('no_enroll_apps_started', models.IntegerField(default=0)),
                ('no_enroll_qhp', models.IntegerField(default=0)),
                ('no_enroll_abe_chip', models.IntegerField(default=0)),
                ('no_enroll_shop', models.IntegerField(default=0)),
                ('no_referrals_agents_brokers', models.IntegerField(default=0)),
                ('no_referrals_ship_medicare', models.IntegerField(default=0)),
                ('no_referrals_other_assis_programs', models.IntegerField(default=0)),
                ('no_referrals_issuers', models.IntegerField(default=0)),
                ('no_referrals_doi', models.IntegerField(default=0)),
                ('no_mplace_tax_form_assis', models.IntegerField(default=0)),
                ('no_mplace_exempt_assis', models.IntegerField(default=0)),
                ('no_qhp_abe_appeals', models.IntegerField(default=0)),
                ('no_data_matching_mplace_issues', models.IntegerField(default=0)),
                ('no_sep_eligible', models.IntegerField(default=0)),
                ('no_employ_spons_cov_issues', models.IntegerField(default=0)),
                ('no_aptc_csr_assis', models.IntegerField(default=0)),
                ('cmplx_cases_mplace_issues', models.CharField(blank=True, default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='NavMetricsLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picmodels.Address')),
            ],
            options={
                'verbose_name_plural': 'Navigator Metrics Locations',
            },
        ),
        migrations.CreateModel(
            name='PICConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('middle_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(default='', max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=1000, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=1000, null=True)),
                ('best_contact_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('household_size', models.IntegerField()),
                ('plan', models.CharField(blank=True, max_length=1000, null=True)),
                ('met_nav_at', models.CharField(max_length=1000)),
                ('date_met_nav', models.DateField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picmodels.Address')),
            ],
        ),
        migrations.CreateModel(
            name='PICStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(default='', max_length=1000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(max_length=1000)),
                ('county', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('mpn', models.CharField(blank=True, default='', max_length=1000)),
                ('staff_pic', models.ImageField(default='staff_pics/None/default_staff.jpg', upload_to='staff_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='PICUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('Miscellaneous', 'Miscellaneous'), ('Health Alliance Medical Plans, Inc.', 'Health Alliance Medical Plans, Inc.'), ('Blue Cross Blue Shield of Illinois', 'Blue Cross Blue Shield of Illinois'), ('Humana Health Plan, Inc.', 'Humana Health Plan, Inc.'), ('Celtic Insurance Company', 'Celtic Insurance Company'), ('Cigna HealthCare of Illinois, Inc.', 'Cigna HealthCare of Illinois, Inc.'), ('Premera Blue Cross Blue Shield of Alaska', 'Premera Blue Cross Blue Shield of Alaska'), ('Blue Cross and Blue Shield of Alabama', 'Blue Cross and Blue Shield of Alabama'), ('QualChoice Life & Health Insurance Company, Inc.', 'QualChoice Life & Health Insurance Company, Inc.'), ('USAble Mutual Insurance Company', 'USAble Mutual Insurance Company'), ('QCA Health Plan, Inc.', 'QCA Health Plan, Inc.'), ('Florida Health Care Plan, Inc.', 'Florida Health Care Plan, Inc.'), ('Medica Insurance Company', 'Medica Insurance Company'), ('CareSource Indiana, Inc.', 'CareSource Indiana, Inc.'), ('Blue Cross and Blue Shield of Arizona, Inc.', 'Blue Cross and Blue Shield of Arizona, Inc.'), ('Blue Cross and Blue Shield of Florida', 'Blue Cross and Blue Shield of Florida'), ('Health Options, Inc.', 'Health Options, Inc.'), ('Aetna Life Insurance Company', 'Aetna Life Insurance Company'), ('Aetna Health Inc. (a PA corp.)', 'Aetna Health Inc. (a PA corp.)'), ('Highmark BCBSD Inc.', 'Highmark BCBSD Inc.'), ('Health Net of Arizona, Inc.', 'Health Net of Arizona, Inc.'), ('Health First Commercial Plans, Inc.', 'Health First Commercial Plans, Inc.'), ('Humana Medical Plan, Inc.', 'Humana Medical Plan, Inc.'), ('Molina Healthcare of Florida, Inc', 'Molina Healthcare of Florida, Inc'), ('Alliant Health Plans', 'Alliant Health Plans'), ('Blue Cross Blue Shield Healthcare Plan of Georgia, Inc.', 'Blue Cross Blue Shield Healthcare Plan of Georgia, Inc.'), ('Kaiser Foundation Health Plan of Georgia', 'Kaiser Foundation Health Plan of Georgia'), ('Ambetter of Peach State Inc.', 'Ambetter of Peach State Inc.'), ('Humana Employers Health Plan of Georgia, Inc.', 'Humana Employers Health Plan of Georgia, Inc.'), ('Wellmark Value Health Plan, Inc.', 'Wellmark Value Health Plan, Inc.'), ('CareSource Kentucky Co.', 'CareSource Kentucky Co.'), ('Gundersen Health Plan, Inc.', 'Gundersen Health Plan, Inc.'), ('Wellmark Synergy Health, Inc.', 'Wellmark Synergy Health, Inc.'), ('Anthem Ins Companies Inc(Anthem BCBS)', 'Anthem Ins Companies Inc(Anthem BCBS)'), ('MDwise Marketplace, Inc.', 'MDwise Marketplace, Inc.'), ('Hawaii Medical Service Association', 'Hawaii Medical Service Association'), ('Kaiser Foundation Health Plan, Inc.', 'Kaiser Foundation Health Plan, Inc.'), ('Aetna Health of Iowa Inc.', 'Aetna Health of Iowa Inc.'), ('BlueCross BlueShield Kansas Solutions, Inc.', 'BlueCross BlueShield Kansas Solutions, Inc.'), ('Blue Cross and Blue Shield of Kansas City', 'Blue Cross and Blue Shield of Kansas City'), ('Anthem Health Plans of KY(Anthem BCBS)', 'Anthem Health Plans of KY(Anthem BCBS)'), ('Humana Health Benefit Plan of Louisiana, Inc.', 'Humana Health Benefit Plan of Louisiana, Inc.'), ('HMO Louisiana, Inc.', 'HMO Louisiana, Inc.'), ('Vantage Health Plan, Inc.', 'Vantage Health Plan, Inc.'), ('Louisiana Health Service & Indemnity Company', 'Louisiana Health Service & Indemnity Company'), ('Maine Community Health Options', 'Maine Community Health Options'), ('Anthem Health Plans of ME(Anthem BCBS)', 'Anthem Health Plans of ME(Anthem BCBS)'), ('Harvard Pilgrim Health Care Inc.', 'Harvard Pilgrim Health Care Inc.'), ('Blue Cross Blue Shield of Michigan Mutual Insurance Company', 'Blue Cross Blue Shield of Michigan Mutual Insurance Company'), ('McLaren Health Plan Community', 'McLaren Health Plan Community'), ('Priority Health', 'Priority Health'), ('Blue Care Network of Michigan', 'Blue Care Network of Michigan'), ('Health Alliance Plan (HAP)', 'Health Alliance Plan (HAP)'), ('Meridian Health Plan of Michigan, Inc.', 'Meridian Health Plan of Michigan, Inc.'), ('Humana Medical Plan of Michigan, Inc.', 'Humana Medical Plan of Michigan, Inc.'), ('Molina Healthcare of Michigan, Inc.', 'Molina Healthcare of Michigan, Inc.'), ('Humana Insurance Company', 'Humana Insurance Company'), ('Physicians Health Plan', 'Physicians Health Plan'), ('Healthy Alliance Life Co(Anthem BCBS)', 'Healthy Alliance Life Co(Anthem BCBS)'), ('Medica Health Plans', 'Medica Health Plans'), ('CareSource', 'CareSource'), ('Montana Health Cooperative', 'Montana Health Cooperative'), ('Cigna Health and Life Insurance Company', 'Cigna Health and Life Insurance Company'), ('AmeriHealth HMO, Inc.', 'AmeriHealth HMO, Inc.'), ('Total Health Care USA, Inc.', 'Total Health Care USA, Inc.'), ('New Mexico Health Connections', 'New Mexico Health Connections'), ('Ambetter of Magnolia Inc.', 'Ambetter of Magnolia Inc.'), ('AultCare Insurance Company', 'AultCare Insurance Company'), ('PacificSource Health Plans', 'PacificSource Health Plans'), ('Blue Cross and Blue Shield of Montana', 'Blue Cross and Blue Shield of Montana'), ('Horizon Healthcare Services, Inc.', 'Horizon Healthcare Services, Inc.'), ('AmeriHealth Ins Company of New Jersey', 'AmeriHealth Ins Company of New Jersey'), ('Medical Health Insuring Corp. of Ohio', 'Medical Health Insuring Corp. of Ohio'), ('Blue Cross Blue Shield of North Dakota', 'Blue Cross Blue Shield of North Dakota'), ('Blue Cross and Blue Shield of NC', 'Blue Cross and Blue Shield of NC'), ('Cigna HealthCare of North Carolina, Inc.', 'Cigna HealthCare of North Carolina, Inc.'), ('Sanford Health Plan', 'Sanford Health Plan'), ('Geisinger Health Plan', 'Geisinger Health Plan'), ('Harvard Pilgrim Health Care of NE', 'Harvard Pilgrim Health Care of NE'), ('Minuteman Health, Inc', 'Minuteman Health, Inc'), ('Matthew Thornton Hlth Plan(Anthem BCBS)', 'Matthew Thornton Hlth Plan(Anthem BCBS)'), ('Community Insurance Company(Anthem BCBS)', 'Community Insurance Company(Anthem BCBS)'), ('Molina Healthcare of New Mexico, Inc.', 'Molina Healthcare of New Mexico, Inc.'), ('CHRISTUS Health Plan', 'CHRISTUS Health Plan'), ('Blue Cross Blue Shield of New Mexico', 'Blue Cross Blue Shield of New Mexico'), ('Prominence HealthFirst', 'Prominence HealthFirst'), ('Rocky Mountain Hospital and Medical Service, Inc., dba Anthem Blue Cross and Blue Shield', 'Rocky Mountain Hospital and Medical Service, Inc., dba Anthem Blue Cross and Blue Shield'), ('HMO Colorado, Inc., dba HMO Nevada', 'HMO Colorado, Inc., dba HMO Nevada'), ('Health Plan of Nevada, Inc.', 'Health Plan of Nevada, Inc.'), ('Molina Healthcare of Ohio, Inc.', 'Molina Healthcare of Ohio, Inc.'), ('Buckeye Community Health Plan', 'Buckeye Community Health Plan'), ('Premier Health Plan, Inc.', 'Premier Health Plan, Inc.'), ('Humana Health Plan of Ohio, Inc.', 'Humana Health Plan of Ohio, Inc.'), ('Paramount Insurance Company', 'Paramount Insurance Company'), ('Consumers Life Insurance Company', 'Consumers Life Insurance Company'), ('Summa Insurance Company, Inc.', 'Summa Insurance Company, Inc.'), ('Moda Health Plan, Inc.', 'Moda Health Plan, Inc.'), ('BridgeSpan Health Company', 'BridgeSpan Health Company'), ('Blue Cross Blue Shield of Oklahoma', 'Blue Cross Blue Shield of Oklahoma'), ('Kaiser Foundation Healthplan of the NW', 'Kaiser Foundation Healthplan of the NW'), ('ATRIO Health Plans', 'ATRIO Health Plans'), ('First Priority Health', 'First Priority Health'), ('Independence Blue Cross (QCC Ins. Co.)', 'Independence Blue Cross (QCC Ins. Co.)'), ('Keystone Health Plan East, Inc', 'Keystone Health Plan East, Inc'), ('Highmark Inc.', 'Highmark Inc.'), ('Highmark Health Insurance Company', 'Highmark Health Insurance Company'), ('UPMC Health Options, Inc.', 'UPMC Health Options, Inc.'), ('Blue Cross and Blue Shield of South Carolina', 'Blue Cross and Blue Shield of South Carolina'), ('Providence Health Plan', 'Providence Health Plan'), ('Capital Advantage Assurance Company', 'Capital Advantage Assurance Company'), ('Avera Health Plans, Inc.', 'Avera Health Plans, Inc.'), ('Unity Health Plans Insurance Corporation', 'Unity Health Plans Insurance Corporation'), ('MercyCare HMO, Inc.', 'MercyCare HMO, Inc.'), ('Blue Cross Blue Shield of Tennessee', 'Blue Cross Blue Shield of Tennessee'), ('Medica Health Plans of Wisconsin', 'Medica Health Plans of Wisconsin'), ('Optima Health Plan', 'Optima Health Plan'), ('Blue Cross Blue Shield of Texas', 'Blue Cross Blue Shield of Texas'), ('Humana Health Plan of Texas, Inc.', 'Humana Health Plan of Texas, Inc.'), ('SHA, LLC DBA FirstCare Health Plans', 'SHA, LLC DBA FirstCare Health Plans'), ('Group Hospitalization and Medical Services Inc.', 'Group Hospitalization and Medical Services Inc.'), ('Kaiser Foundation Health Plan of the Mid-Atlantic States, Inc.', 'Kaiser Foundation Health Plan of the Mid-Atlantic States, Inc.'), ('HealthKeepers, Inc.', 'HealthKeepers, Inc.'), ('Sendero Health Plans, inc.', 'Sendero Health Plans, inc.'), ('Oscar Insurance Company of Texas', 'Oscar Insurance Company of Texas'), ('Community Health Choice, Inc.', 'Community Health Choice, Inc.'), ('Piedmont Community HealthCare, Inc.', 'Piedmont Community HealthCare, Inc.'), ('Prominence HealthFirst of Texas, Inc.', 'Prominence HealthFirst of Texas, Inc.'), ('Innovation Health Insurance Company', 'Innovation Health Insurance Company'), ('UnitedHealthcare of the Mid-Atlantic Inc', 'UnitedHealthcare of the Mid-Atlantic Inc'), ('Molina Healthcare of Texas, Inc.', 'Molina Healthcare of Texas, Inc.'), ('Piedmont Community HealthCare HMO, Inc.', 'Piedmont Community HealthCare HMO, Inc.'), ('CareFirst BlueChoice, Inc.', 'CareFirst BlueChoice, Inc.'), ('SelectHealth', 'SelectHealth'), ('Molina Healthcare of Utah', 'Molina Healthcare of Utah'), ('University of Utah Health Insurance Plans', 'University of Utah Health Insurance Plans'), ('Group Health Cooperative of South Central Wisconsin', 'Group Health Cooperative of South Central Wisconsin'), ('Health Tradition Health Plan', 'Health Tradition Health Plan'), ("Children's Community Health Plan", "Children's Community Health Plan"), ('CareSource West Virginia Co.', 'CareSource West Virginia Co.'), ('Security Health Plan of Wisconsin, Inc.', 'Security Health Plan of Wisconsin, Inc.'), ('Dean Health Plan', 'Dean Health Plan'), ('Aspirus Arise Health Plan of Wisconsin, Inc.', 'Aspirus Arise Health Plan of Wisconsin, Inc.'), ('Molina Healthcare of Wisconsin, Inc.', 'Molina Healthcare of Wisconsin, Inc.'), ('Compcare Health Serv Ins Co(Anthem BCBS)', 'Compcare Health Serv Ins Co(Anthem BCBS)'), ('Common Ground Healthcare Cooperative', 'Common Ground Healthcare Cooperative'), ('HealthPartners Insurance Company', 'HealthPartners Insurance Company'), ('Network Health Plan', 'Network Health Plan'), ('Highmark Blue Cross Blue Shield West Virginia', 'Highmark Blue Cross Blue Shield West Virginia'), ('Blue Cross Blue Shield of Wyoming', 'Blue Cross Blue Shield of Wyoming')], default='Miscellaneous', max_length=1000)),
                ('premium_type', models.CharField(blank=True, choices=[('HMO', 'HMO'), ('PPO', 'PPO'), ('POS', 'POS'), ('EPO', 'EPO'), ('Not Available', 'Not Available')], default='Not Available', max_length=1000, null=True)),
                ('metal_level', models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Catastrophic', 'Catastrophic'), ('Not Available', 'Not Available')], default='Not Available', max_length=1000, null=True)),
                ('enrollments', models.IntegerField()),
                ('metrics_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picmodels.MetricsSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='picmodels.PICStaff')),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='picstaff',
            name='base_locations',
            field=models.ManyToManyField(blank=True, to='picmodels.NavMetricsLocation'),
        ),
        migrations.AddField(
            model_name='picconsumer',
            name='navigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='picmodels.PICStaff'),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='picmodels.NavMetricsLocation'),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picmodels.PICStaff'),
        ),
        migrations.AddField(
            model_name='consumernote',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picmodels.PICConsumer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picmodels.PICConsumer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picmodels.Location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='poc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='picmodels.PICStaff'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picmodels.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='picconsumer',
            unique_together=set([('first_name', 'last_name', 'met_nav_at', 'household_size')]),
        ),
        migrations.AlterUniqueTogether(
            name='navmetricslocation',
            unique_together=set([('address', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('address_line_1', 'address_line_2', 'zipcode', 'city', 'state_province', 'country')]),
        ),
    ]
