# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picmodels', '0003_auto_20170117_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumercpsinfoentry',
            name='apt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumercpsinfoentry',
            name='case_mgmt_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Silver'), ('Not Available', 'Not Available')], default='Not Available', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consumercpsinfoentry',
            name='case_mgmt_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consumercpsinfoentry',
            name='phone_apt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumercpsinfoentry',
            name='target_list',
            field=models.BooleanField(default=False),
        ),
    ]
