# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picmodels', '0004_auto_20170117_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumercpsinfoentry',
            name='app_status',
            field=models.CharField(blank=True, choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Not Available', 'Not Available')], default='Not Available', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='consumercpsinfoentry',
            name='app_type',
            field=models.CharField(blank=True, choices=[('Medicaid', 'Medicaid'), ('SNAP', 'SNAP'), ('Not Available', 'Not Available')], default='Not Available', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='consumercpsinfoentry',
            name='case_mgmt_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Resloved', 'Resolved'), ('Not Available', 'Not Available')], default='Not Available', max_length=1000, null=True),
        ),
    ]
