# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picmodels', '0013_remove_metricssubmission_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricssubmission',
            name='applied_medicaid',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='filed_exemptions',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='hardship_or_difficulty',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='outreach_activity',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='rec_postenroll_support',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='received_education',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='ref_medicaid_or_chip',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='selected_qhp',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='success_story',
        ),
        migrations.RemoveField(
            model_name='metricssubmission',
            name='trends',
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='cmplx_cases_mplace_issues',
            field=models.CharField(blank=True, max_length=5000, default=''),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_aptc_csr_assis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_billing_assis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_data_matching_mplace_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_employ_spons_cov_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_enroll_abe_chip',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_enroll_apps_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_enroll_qhp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_enroll_shop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_general_assis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_locating_provider_assis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_mplace_exempt_assis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_mplace_tax_form_assis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_plan_usage_assis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_qhp_abe_appeals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_referrals_agents_brokers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_referrals_doi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_referrals_issuers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_referrals_other_assis_programs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_referrals_ship_medicare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metricssubmission',
            name='no_sep_eligible',
            field=models.IntegerField(default=0),
        ),
    ]
