# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picmodels', '0033_auto_20161228_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='picstaff',
            name='staff_pic',
            field=models.ImageField(default='staff_pics/None/default_staff.jpg', upload_to='staff_pics/'),
        ),
    ]
